### ISSUE TITLE
Automatic unloading of (job)helper addons.

### ISSUE THREAD

**Issue by llogical** [GetAwayCoxn/Ashita-v4-Addons#1]
Would it be a thing to unload these helper addons once there is a job change?

**Comment by GetAwayCoxn** [comment]
That is possible sure but I am curious why you want to do that? The job specific addons should all self hide/disable if not on the appropriate job iirc so no real need to actually unload them. What is it you are trying to accomplish?

**Comment by GetAwayCoxn** [comment]
Ahhh I see, thanks for the input and reply, enjoy!
